= Ronetix FSL community based BSP platform for i.MX7-CM and i.MX8M-CM

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

[source,console]
$: sudo apt install bmap-tools

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir yocto-ronetix
$: cd yocto-ronetix
$: repo init -u https://github.com/ronetix/bsp-repo -b zeus
$: repo sync

At the end of the commands you have every metadata you need to start work with.

i.MX7-CM: to start a simple image build:
----------------------------------------

[source,console]
$: MACHINE=imx7-cm DISTRO=fslc-x11 . setup-environment build_x11
$: bitbake fsl-image-gui

Creating a bootable SD card:

[source,console]
umount /dev/sdc1
umount /dev/sdc2
sudo bmaptool copy tmp/deploy/images/imx7-cm/fsl-image-gui-imx7-cm.wic.gz /dev/sdc


i.MX8M-CM: to start a simple image build:
-----------------------------------------

[source,console]
$: MACHINE=imx8m_cm DISTRO=fslc-xwayland . setup-environment build_xwayland_mx8m_cm
$: bitbake fsl-image-ronetix

Creating a bootable SD card:

[source,console]
umount /dev/sdc1
umount /dev/sdc2
sudo bmaptool copy tmp/deploy/images/imx8m-cm/fsl-image-ronetix-imx8m-cm.wic.gz /dev/sdc

== Contributing

To contribute to this layer you should send the patches for review to: support [AT] ronetix.at



